config/routes.rb
Rails.application.routes.draw do
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # devise_for :users
  post 'auth_user' => 'authentication#authenticate_user'
  root 'home#index'
  get "test", to: "home#test"
  resources :users
  resources :purchases
  get "purchases-list", to: "purchases#list"
  # resources :purchases, only:[:index, ] do
  # end
  # get 'home/index'

  ## API
  namespace :api do
    namespace :v1 do
      resources :users
      resources :purchases
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
    belongs_to :user, optional: true
    mount_uploader :image, PictureUploader
    # validates :image, presence: true

    CATEGORIES= %w(categoria1 categoria2 categoria3)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # has_secure_password
  has_many :purchases
  
  ROLES= %w(admin user)

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/purchases_controller.rb
class Api::V1::PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :update, :destroy]
  before_action :authenticate_request!
  
  # GET /api/v1/purchases
	def index
		@purchases = Purchase.all
		@purchases = current_user.purchases unless current_user.admin?
		render json: @purchases
  end
	
  # GET /api/v1/purchases/1
  def show
    render json: @purchase
  end

  # POST /api/v1/purchases
  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.user_id = current_user.id
    @purchase.user = current_user
    if current_user.admin?
      @user = User.find(purchase_params[:user_id])
      @purchase.user_id = @user.id
      @purchase.user = @user
    end

    if @purchase.save
      render json: @purchase, status: :created, location: api_v1_purchase_url(@purchase)
    else
      render json: @purchase.errors, status: :unprocessable_entity
    end
  end
  
  # PATCH/PUT /purchases/1
  def update
    if @purchase.update(purchase_params)
    render json: @purchase
    else
    render json: @purchase.errors, status: :unprocessable_entity
    end
  end
  
  # DELETE /purchases/1
  def destroy
    @purchase.destroy
  end

  private
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    def purchase_params
      params.require(:purchase).permit(:description, :user_id) # if params[:purchase]
    end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
	before_action :authenticate_request!

	def index
		@users = User.all if current_user.admin?
		render json: @users
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  attr_reader :current_user
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

  def mobile_device
    agent = request.user_agent
    return "tablet" if agent =~ /(tablet|ipad)|(android(?!.*mobile))/i
    return "mobile" if agent =~ /Mobile/
    return "desktop"
  end

  protected
  def authenticate_request!
    unless user_id_in_token?
      render json: { errors: ['Not Authenticated'] }, status: :unauthorized
      return
    end
    @current_user = User.find(auth_token[:user_id])
  rescue JWT::VerificationError, JWT::DecodeError
    render json: { errors: ['Not Authenticated'] }, status: :unauthorized
  end

  private
  def http_token
      @http_token ||= if request.headers['Authorization'].present?
        request.headers['Authorization'].split(' ').last
      end
  end

  def auth_token
    @auth_token ||= JsonWebToken.decode(http_token)
  end

  def user_id_in_token?
    http_token && auth_token && auth_token[:user_id].to_i
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  # Can't verify CSRF token authenticity.
  skip_before_action :verify_authenticity_token

  def authenticate_user
    user = User.find_for_database_authentication(email: params[:email])
    if user.valid_password?(params[:password])
      render json: payload(user)
    else
      render json: {errors: ['Invalid Username/Password']}, status: :unauthorized
    end
  end

  private

  def payload(user)
    return nil unless user and user.id
    {
      auth_token: JsonWebToken.encode({user_id: user.id}),
      user: {id: user.id, email: user.email}
    }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_request!
  
  def index
  end

  def test
    render json: {'logged_in' => true}
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
	include SessionsHelper
	before_action :set_purchase, only: [:show, :edit, :update, :destroy]

	def index
		if logged_in?
			if current_user.admin?
				@purchases = Purchase.all.order(:id)
			else
				@purchases = Purchase.where(user_id: current_user.id).order(:id)
			end
		end
	end

	def list
		@purchases = Purchase.all
	end

	def new
		@purchase = Purchase.new
		# authorize @purchase
	end

	def edit
	end

	def update
		if @purchase.update purchase_params
			redirect_to purchase_path(@purchase), notice: "El Pedido ##{@purchase.id} se modificó correctamente."
		else
			render :edit, alert: 'Error en:'
		end
	end

	def create
		@purchase = Purchase.new(purchase_params)
    if @purchase.save
      redirect_to purchase_path(@purchase), notice: "El Pedido-#{@purchase.id} se creó correctamente."
    else
      render :new, alert: 'Error en:'
    end
	end

	def show
	end

	def destroy
		if @purchase.destroy
			redirect_to purchases_path, notice: "Pedido ##{@purchase.id} eliminado."
		else
			redirect_to purchases_path, notice: "No se puede eliminar Pedido ##{@purchase.id}"
		end
  end

	private
		def set_purchase
			@purchase = Purchase.find(params[:id])
		end

		def purchase_params
			params.require(:purchase).permit(:description, :category, :image, :user_id,
				:status, :delivery_date, :reception_date)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.valid_password?(params[:session][:password])
      log_in user
      redirect_to purchases_path
    else
      flash.now[:danger] = 'Email o password inválidos'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :show]

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user =User.new
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to [@user], notice: 'Usuario ha sido creado' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, alert: 'Se encontraron errores. Revisar por favor' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
	end

	def edit
	end

	def update
		if @user.update user_params
			redirect_to users_path, notice: "El Usuario #{@user.full_name} se modificó correctamente."
		else
			render :edit, alert: 'Error en:'
		end
	end

	def show
	end

	private
		def user_params
			# policy(@user).permitted_attributes
			params.require(:user).permit(:full_name, :email, :password, :password_confirmation)
		end
		def set_user
			@user = User.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
	def current_class?(test_path)
    return true if request.path == test_path
    false
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
          User.find_by(id: session[:user_id])
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/views/home/index.html.slim
.jumbotron
	- if logged_in?
		h1
			|Bienvenido #{current_user.full_name}! (:
		p class="lead"
			|Esta web permite la administración de tus pedidos.
	- else
		h1 
			|Bienvenido! (:
		p class="lead"
			|Esta web permite la administración de pedidos.
  
	hr class="my-4"

	- unless logged_in?
		p
			|Para empezar, por favor inicia sesión.
		a class="btn btn-info btn-lg" href=login_path role="button"
			|Log in

	- if logged_in?
		.btn-group
			a class="btn btn-info btn-lg" href=purchases_path role="button"
				|Ver Lista de Pedidos
</div>

app/views/layouts/_form_errors.html.slim
- if object.errors.any?
  .alert.alert-danger
    | Por favor revisar:
    ul
      - object.errors.full_messages.each do |msg|
        li= msg

app/views/layouts/application.html.slim
doctype html
html
  head
    title Tektest
    link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags

    meta name="viewport" content="width=device-width, initial-scale=1"

  body
    nav class="navbar navbar-expand-lg navbar-dark bg-info"
      a class="navbar-brand" href=root_path
        | TEST-TEK
      button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation"
        span class="navbar-toggler-icon"

      div class="collapse navbar-collapse" id="navbarTogglerDemo02"
        ul class="navbar-nav mr-auto mt-2 mt-lg-0"
          / li class=(current_class?(root_path) ? 'nav-item active' : 'nav-item')
            a class="nav-link" href=root_path
              | Home
              span class="sr-only" 
              | (current)
          - if logged_in?
            li class=(current_class?(purchases_path) ? 'nav-item active' : 'nav-item')
              a class="nav-link" href=purchases_path
                | Pedidos
            - if current_user.admin?
              li class=(current_class?(users_path) ? 'nav-item active' : 'nav-item')
                a class="nav-link" href=users_path
                  | Usuarios
              li class=(current_class?(users_path) ? 'nav-item active' : 'nav-item')
                a class="nav-link" href="#"
                  | Sesiones

        .form-inline.my-2.my-lg-0
          - if logged_in?
            = link_to user_path(current_user), class: 'purchase-link' do
              span style="color: #fff;" 
                = current_user.full_name 
              i class="fas fa-user" style="font-size: 1.3rem; padding-right: 15px; color: #fff; padding-left: 5px;"

            = link_to logout_path, method: :delete, class: 'purchase-link' do
              span style="color: #fff;" 
                |Log Out 
              i class="fas fa-sign-out-alt" style="font-size: 1.3rem; padding-right: 15px; color: #fff;;"
          - else
            a class="nav-link" href=login_path style="color: #fff;"
              |Log In 
              span class="fas fa-sign-in-alt" style="font-size: 1.3rem; padding-right: 15px; color: #fff;"


      / header.navbar
      /   .logo
      /     = link_to "Spy app", 'root_path', id: "logo"
      /     nav
      /       ul.navbar-right
      /         li
      /           = link_to "Home",    'root_path'
      /         li
      /           = link_to "Help",    'help_path'
      /         li
      /           = link_to "Sign up", 'sign_up_path'
      /         li
      /           = link_to "Log in",  'login_path'
    
    br
    .container
      = yield

app/views/purchases/_cards.html.slim
.row
	- purchases.each do |purchase|
		.col-sm-3.space-before
			.card-deck
				a class="card-link" href=purchase_path(purchase)
					.card 
						img class="card-img-top" src="#{ purchase.image }" alt="Card image cap" height="200px"
						.card-body style="color: #212529; height: 150px"
							h5 class="card-title"
								| Pedido ##{purchase.id}
							p class="card-text"
								= purchase.description
						.card-footer
							small class="text-muted" Last updated 3 mins ago

app/views/purchases/_form.html.slim
= simple_form_for([@purchase]) do |f|
	= render "layouts/form_errors", object: f.object

	= f.input :description, label: 'Descripción', :input_html => { :class => "" }
	= f.file_field :image, as: :file
	= f.input :category, as: :select, collection: Purchase::CATEGORIES, label: 'Categorías'
	= f.input :address, label: 'Dirección de destino', :input_html => { :class => "" }
	= f.input :delivery_date, label: "Fecha de Envío", :start_year => 2018
	= f.input :status, label: "Entregado?", :input_html => { :class => "checkbox" }
	= f.input :reception_date, label: "Fecha de Recepción"
	= f.input :user_id, as: :select, collection: User.all.order(:full_name), :label_method => :full_name, :value_method => :id

	= f.submit "Guardar", class:"btn btn-info"

app/views/purchases/_list.html.slim
- if purchases.length > 0
	.table-responsive
		table class="table table-striped"
			thead
				tr
					th scope="col"
						|Nombre
					th scope="col"
						|Comprador
					th scope="col"
						|Estado
					th scope="col"
						|Acción
			tbody
				- purchases.each do |purchase|
					tr
						th scope="row"
							| Pedido #{purchase.id}
						td
							=purchase.user.full_name if purchase.user.present?
						td
							=purchase.status
						td
							=link_to edit_purchase_path(purchase) do
								i class="fas fa-edit ffa-w-10" style="font-size: 1.3rem; padding-right: 15px; color: #17a2b8;"
							=link_to purchase_path(purchase), method: :delete do
								i class="fas fa-trash-alt ffa-w-10" style="font-size: 1.3rem; padding-right: 15px; color: #dc3545;"

app/views/purchases/edit.html.slim
h1 Editar Pedido ##{@purchase.id}
hr

- if notice.present?
  .alert.alert-info
    = notice

== render 'form'
hr
a href=purchases_path class="back"
	span class="fas fa-chevron-left" style="padding-right:10px;"
	|regresar

app/views/purchases/index.html.slim
h1 
	|Pedidos

hr

nav class="nav"
	.purchase-link
		= link_to new_purchase_path, class: 'purchase-link' do
			span style="font-size: 1.3rem; color: #6c757d;" 
				|Nuevo 
			i class="fas fa-plus ffa-w-10" style="font-size: 1.3rem; padding-right: 15px; color: #17a2b8;"

	= link_to purchases_path do
		span style="font-size: 1.3rem; color: #6c757d;" 
			| 
		i class="fas fa-grip-horizontal  ffa-w-10" style="font-size: 1.3rem; padding-right: 15px; color: #17a2b8;"

	= link_to purchases_path(:list_view => true) do
		span style="font-size: 1.3rem; color: #6c757d;" 
			| 
		i class="fas fa-list-ul ffa-w-10" style="font-size: 1.3rem; padding-right: 15px; color: #17a2b8;"
  

- if notice.present?
  .alert.alert-info
    = notice

br

- if params[:list_view].present?
	= render "list", purchases: @purchases
- else
	= render "cards", purchases: @purchases

app/views/purchases/new.html.slim
h1 Nuevo Pedido
hr

- if notice.present?
  .alert.alert-info
    = notice

== render 'form'
hr
a href=purchases_path class="back"
	span class="fas fa-chevron-left" style="padding-right:10px;"
	| regresar

app/views/purchases/show.html.slim
h1
  |Pedido ##{@purchase.id}
hr

nav class="nav"
	.purchase-link
		= link_to new_purchase_path, class: 'purchase-link' do
			span style="font-size: 1.3rem; color: #6c757d;" 
				|Nuevo 
			i class="fas fa-plus ffa-w-10" style="font-size: 1.3rem; padding-right: 15px; color: #17a2b8;"
    = link_to edit_purchase_path(@purchase) do
      span style="font-size: 1.3rem; color: #6c757d;" 
        | Editar 
      i class="fas fa-edit  ffa-w-10" style="font-size: 1.3rem; padding-right: 15px; color: #17a2b8;"
    = link_to purchases_path do
      span style="font-size: 1.3rem; color: #6c757d;" 
        | Ir a Pedidos 
      i class="fas fa-grip-horizontal  ffa-w-10" style="font-size: 1.3rem; padding-right: 15px; color: #17a2b8;"

- if notice.present?
  .alert.alert-info= notice

br

h3 Descripción
p 
  =@purchase.description

h3 Imagen
- if @purchase.image.present?
  img class="img-fluid img-thumbnail" src="#{ @purchase.image }" alt="Card image cap" width="200px"

app/views/users/_form.html.slim
= simple_form_for([@user]) do |f|
	= render "layouts/form_errors", object: f.object

	= f.input :full_name, label: 'Nombre y Apellido', :input_html => { :class => "" }
	= f.input :email, label: 'Email'
    = f.input :password, label: 'Contraseña'

	= f.submit "Guardar", class:"btn btn-info"

app/views/users/edit.html.slim
h1 Editar Usuario
hr

- if notice.present?
  .alert.alert-info
    = notice

== render 'form'
hr
a href=users_path class="back"
	span uk-icon="fas fa-caret-left"
	| regresar

app/views/users/index.html.slim
h1 
	|Usuarios

hr

- if notice.present?
  .alert.alert-info
    = notice

nav class="nav"
	.purchase-link
		= link_to new_user_path, class: 'purchase-link' do
			span style="font-size: 1.3rem; color: #6c757d;" 
				|Nuevo 
			i class="fas fa-user-plus ffa-w-10" style="font-size: 1.3rem; padding-right: 15px; color: #17a2b8;"

br

- if @users.length > 0
	.table-responsive
		table class="table table-striped"
			thead
				tr
					th scope="col"
						|#
					th scope="col"
						|Nombre
					th scope="col"
						|Correo
					th scope="col"
						|Role
					th scope="col"
						|Acción
			tbody
				- @users.each do |user|
					tr
						th scope="row"
							=user.id
						td
							=user.full_name
						td
							=user.email
						td
							=user.role
						td
							=link_to edit_user_path(user) do
								i class="fas fa-edit ffa-w-10" style="font-size: 1.3rem; padding-right: 15px; color: #17a2b8;"

app/views/users/new.html.slim
h1 Nuevo Usuario
hr

- if notice.present?
  .alert.alert-info
    = notice

== render 'form'
hr
a href=users_path class="back"
	span uk-icon="icon: chevron-left; ratio: 1.1"
	| regresar

app/views/users/show.html.slim
h1
  |Hola #{@user.full_name}!
hr

- if notice.present?
  .alert.alert-info= notice

h3 Nombre
p 
	=@user.full_name

h3 Email
p 
	=@user.email